version: "3.9"

services:
  app:
    image: dockerfile
    container_name: app
    build:
      context: ./messaging
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    ports:
      - 80:80
  mysql:
    image: mysql:8.0.25
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: messaging
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
